"""add language to questions

Revision ID: 2c62a31a9031
Revises: 19042706a040
Create Date: 2026-08-14 03:31:26.064700

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c62a31a9031"
down_revision: str | Sequence[str] | None = "19042706a040"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column(
            "language", sa.String(length=10), server_default="ja", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "language")
    # ### end Alembic commands ###
