"""add type and chunk_index to question embeddings

Revision ID: 4a29086da7e1
Revises: 4ce2611e20d5
Create Date: 2026-08-09 15:11:47.325934

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a29086da7e1'
down_revision: str | Sequence[str] | None = '4ce2611e20d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_embeddings', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('question_embeddings', sa.Column('chunk_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_embeddings', 'chunk_index')
    op.drop_column('question_embeddings', 'type')
    # ### end Alembic commands ###
